/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package practica7;

import Clases.Conexion;
import Clases.Empleado;
import Clases.Producto;
import javax.swing.JOptionPane;
import static javax.swing.JOptionPane.ERROR_MESSAGE;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;
import javax.swing.table.TableRowSorter;

/**
 *
 * @author DELL
 */
public class GestionProductos extends javax.swing.JFrame {
    Conexion cliente;
    private int columnas=7;
    private String[] columna; // columnas de la tabla
    private DefaultTableModel model_productos; // modelo de la tabla
    Empleado empleado;
    public GestionProductos(Conexion cli,Empleado emp) {
        cliente = cli;
        empleado=emp;
        model_productos = new DefaultTableModel(null,getColumnas()){ // inicializar el modelo de la tabla
            @Override
            public boolean isCellEditable(int fila, int columna) {
                return false;
            }
        };
        
        
        initComponents();
        this.setLocationRelativeTo(null);
        
        this.setTitle("Productos registrados");
        tablaProductos.getTableHeader().setReorderingAllowed(false); //evitar que las columnas se editen
        this.setLocationRelativeTo(null); // centrar frame
        //llenar la tabla con todos los registros de la sucursal
        //LlenarTable("select (idUsuario,nombre,apellidoPaterno,apellidoMaterno,direccion,idRol) from usuarios");
        LlenarTable("select (productos.idProducto, productos.nombreProd, productos.existencia,productos.precioUnidad,"
                + "productos.precioProveedor,productos.descripcionProd,categorias.nombreCat) from productos inner join "
                + "categorias on productos.idCategoriaFK=categorias.idCategoria");
    }
    //le agregamos las columans a la tabla
    private String[] getColumnas(){ // columnas para la tabla
        return columna =  new String[]{"clave producto","Nombre","Existencia","Precio/U","Precio Proveedor","Descripcion","Categoria"};
    }
    
    private void LlenarTable(String query){
        for (int i = (model_productos.getRowCount() - 1); i >= 0; i--) // limpiamos tabla
            model_productos.removeRow(i);
//        28ae5f6449
        TableRowSorter<TableModel> orden = new TableRowSorter<TableModel>((DefaultTableModel)tablaProductos.getModel()); // modelo para la tabla
        tablaProductos.setRowSorter(orden); // add el ordenamiento
        String [][] res=cliente.consultaSelect(query);
        // recorremos el resultado de la ocnsulta
        for(int j=1;j<res.length;j++){
            model_productos.addRow(res[j]); // add a el modelo de l atabla
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablaProductos = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel1.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setText("Gestion de Productos");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(243, 59, -1, -1));

        tablaProductos.setModel(model_productos);
        jScrollPane1.setViewportView(tablaProductos);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 197, 610, 208));

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/plus (1).png"))); // NOI18N
        jButton1.setText("Alta");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 109, -1, -1));

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/eraser.png"))); // NOI18N
        jButton2.setText("Borrar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(275, 109, -1, -1));

        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/pencil.png"))); // NOI18N
        jButton3.setText("Editar");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(504, 109, -1, -1));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/pills (2).png"))); // NOI18N
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(201, 59, -1, -1));

        jButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/back (1).png"))); // NOI18N
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 11, 33, -1));

        jButton5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/house (3).png"))); // NOI18N
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(279, 11, 33, -1));

        jButton6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/error.png"))); // NOI18N
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton6, new org.netbeans.lib.awtextra.AbsoluteConstraints(587, 11, 33, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 634, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 427, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        AltaProductos ob = new AltaProductos(cliente,1,null,empleado);
        ob.setVisible(true);
        this.setVisible(false);
        this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
       System.exit(0);       // TODO add your handling code here:
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
         MenuPrincipal nn = new MenuPrincipal(cliente,empleado);
         nn.setVisible(true);
         this.setVisible(false);
         this.dispose();
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        MenuPrincipal nn1 = new MenuPrincipal(cliente,empleado);
         nn1.setVisible(true);
         this.setVisible(false);
         this.dispose();
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        int row = tablaProductos.getSelectedRow();
        //comprobamos que este seleccionando un usuario en la tabla
        if(row==-1){
            JOptionPane.showMessageDialog(null, "Seleccione un registro.", "Error", ERROR_MESSAGE);
        }else{
            //obtenemos el id del usuario
            int clave=Integer.parseInt(tablaProductos.getValueAt(row, 0).toString());
            String[][] emp = cliente.consultaSelect("select * from productos where (idProducto="+clave+")");
            int i=Integer.parseInt(emp[1][0]);
            //hacemos un objeto tipo producto y lo mandamos a otra interfaz para llenar el formulario
            Producto producto = new Producto(convint(emp[1][0]),emp[1][1],convint(emp[1][2]),convint(emp[1][3]),convint(emp[1][4]),emp[1][5],convint(emp[1][6]));
            AltaProductos alta = new AltaProductos(cliente,2,producto,empleado);
            alta.setVisible(true);
            this.setVisible(false);
            this.dispose();
        }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        //comprobamos que este seleccionando un usuario
        int row = tablaProductos.getSelectedRow();
        if(row==-1){
            JOptionPane.showMessageDialog(null, "Seleccione un registro.", "Error", ERROR_MESSAGE);
        }else{
            //preguntamos si quiere eliminar el usuario
            if(JOptionPane.showConfirmDialog(null, "Eliminar producto?", "Confirmar",1)==0){
                //preguntamos si esta seguro de hacer la eliminacion e la tabla
                if(JOptionPane.showConfirmDialog(null, "Estas seguro de eliminar el producto?", "Confirmar",1)==0){
                    //obtenemos el id del usuario
                    int clave=Integer.parseInt(tablaProductos.getValueAt(row, 0).toString());
                    //mandamos la consulta para eliminarlo
                    String respuesta = cliente.consultaInsert("delete from productos where (idProducto="+clave+")");
                    if(respuesta.equalsIgnoreCase("Exito")){
                        //actualizamos la pantalla
                        actualizarPantalla();
                    }
                }
            }
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    //actualizamos la ventana actual, cuando se haga un cambio
    public void actualizarPantalla(){
        this.setVisible(false);
        GestionProductos asd = new GestionProductos(cliente,empleado);
        asd.setVisible(true);
    }
    public int convint(String ar){
        return Integer.parseInt(ar);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTable tablaProductos;
    // End of variables declaration//GEN-END:variables
}
