package practica7;

import Clases.Conexion;
import Clases.Empleado;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author DELL
 */
public class MenuPrincipal extends javax.swing.JFrame {
    Conexion cliente;
    Empleado empleado;
    /**
     * Creates new form h
     */
    public MenuPrincipal(Conexion con,Empleado emp) {
        cliente=con;
        empleado=emp;
        initComponents();
        this.setLocationRelativeTo(null);
        if(empleado.getIdRol()==2){
            BtnCorteCaja.setEnabled(false);
            BtnGestionEmpleados.setEnabled(false);
            BtnGestionProductos.setEnabled(false);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        BtnVenta = new javax.swing.JButton();
        BtnCorteCaja = new javax.swing.JButton();
        BtnGestionEmpleados = new javax.swing.JButton();
        BtnGestionProductos = new javax.swing.JButton();
        BtnSalir = new javax.swing.JButton();
        BtnBusqueda = new javax.swing.JButton();
        BtnLogOut = new javax.swing.JButton();
        BtnRegistroV2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setText("Menú");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 20, -1, -1));

        BtnVenta.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/payment-method.png"))); // NOI18N
        BtnVenta.setText("Realizar Venta");
        BtnVenta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnVentaActionPerformed(evt);
            }
        });
        jPanel1.add(BtnVenta, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 80, 170, -1));

        BtnCorteCaja.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/cash-register.png"))); // NOI18N
        BtnCorteCaja.setText("Corte de Caja");
        BtnCorteCaja.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnCorteCajaActionPerformed(evt);
            }
        });
        jPanel1.add(BtnCorteCaja, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 130, 170, -1));

        BtnGestionEmpleados.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/employee (1).png"))); // NOI18N
        BtnGestionEmpleados.setText("Gestion Empleados");
        BtnGestionEmpleados.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnGestionEmpleadosActionPerformed(evt);
            }
        });
        jPanel1.add(BtnGestionEmpleados, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 180, 170, -1));

        BtnGestionProductos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/pills.png"))); // NOI18N
        BtnGestionProductos.setText("Gestion Productos");
        BtnGestionProductos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnGestionProductosActionPerformed(evt);
            }
        });
        jPanel1.add(BtnGestionProductos, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 230, 170, -1));

        BtnSalir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/error.png"))); // NOI18N
        BtnSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnSalirActionPerformed(evt);
            }
        });
        jPanel1.add(BtnSalir, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 20, 33, -1));

        BtnBusqueda.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/research.png"))); // NOI18N
        BtnBusqueda.setText("Busqueda");
        BtnBusqueda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnBusquedaActionPerformed(evt);
            }
        });
        jPanel1.add(BtnBusqueda, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 280, 170, -1));

        BtnLogOut.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/exit (1).png"))); // NOI18N
        BtnLogOut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnLogOutActionPerformed(evt);
            }
        });
        jPanel1.add(BtnLogOut, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 310, 33, -1));

        BtnRegistroV2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/form.png"))); // NOI18N
        BtnRegistroV2.setText("Registro Ventas");
        BtnRegistroV2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnRegistroV2ActionPerformed(evt);
            }
        });
        jPanel1.add(BtnRegistroV2, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 330, 170, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 391, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 405, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BtnVentaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnVentaActionPerformed
        RealizarVenta obj = new RealizarVenta(cliente,empleado);
        obj.setVisible(true);
        this.setVisible(false);
        this.dispose();
    }//GEN-LAST:event_BtnVentaActionPerformed

    private void BtnCorteCajaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnCorteCajaActionPerformed
        RealizarCorte obj = new RealizarCorte(cliente,empleado);
        obj.setVisible(true);
        this.setVisible(false);
        this.dispose();
    }//GEN-LAST:event_BtnCorteCajaActionPerformed

    private void BtnGestionEmpleadosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnGestionEmpleadosActionPerformed
        GestionEmpleados ge = new GestionEmpleados(cliente,empleado);
        ge.setVisible(true);
        this.setVisible(false);
        this.dispose();
    }//GEN-LAST:event_BtnGestionEmpleadosActionPerformed

    private void BtnGestionProductosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnGestionProductosActionPerformed
        GestionProductos gp = new GestionProductos(cliente,empleado);
        gp.setVisible(true);
        this.setVisible(false);
        this.dispose();
    }//GEN-LAST:event_BtnGestionProductosActionPerformed

    private void BtnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnSalirActionPerformed
        System.exit(0);        // TODO add your handling code here:
    }//GEN-LAST:event_BtnSalirActionPerformed

    private void BtnBusquedaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnBusquedaActionPerformed
        Busqueda bu = new Busqueda(cliente,empleado);
        bu.setVisible(true);
        this.setVisible(false);
        this.dispose();
    }//GEN-LAST:event_BtnBusquedaActionPerformed

    private void BtnLogOutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnLogOutActionPerformed
        LogIn login = new LogIn();
        login.setVisible(true);
        this.setVisible(false);
        this.dispose();
    }//GEN-LAST:event_BtnLogOutActionPerformed

    private void BtnRegistroV2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnRegistroV2ActionPerformed
        RegistroVentas rv = new RegistroVentas(cliente,empleado);
        rv.setVisible(true);
        this.setVisible(false);
        this.dispose();
    }//GEN-LAST:event_BtnRegistroV2ActionPerformed



    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnBusqueda;
    private javax.swing.JButton BtnCorteCaja;
    private javax.swing.JButton BtnGestionEmpleados;
    private javax.swing.JButton BtnGestionProductos;
    private javax.swing.JButton BtnLogOut;
    private javax.swing.JButton BtnRegistroV2;
    private javax.swing.JButton BtnSalir;
    private javax.swing.JButton BtnVenta;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
