/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package practica7;

import Clases.Conexion;
import Clases.Empleado;
import java.text.SimpleDateFormat;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;
import javax.swing.table.TableRowSorter;

/**
 *
 * @author DELL
 */
public class RegistroVentas extends javax.swing.JFrame {
    Conexion cliente;
    Empleado empleado;
    private DefaultTableModel model_corte; // modelo de la tabla
    /**
     * Creates new form w
     */
    public RegistroVentas(Conexion cli,Empleado emp) {
        cliente=cli;
        empleado=emp;
        model_corte = new DefaultTableModel(null,getColumnas()){ // inicializar el modelo de la tabla
            @Override
            public boolean isCellEditable(int fila, int columna) {
                return false;
            }
        };
        initComponents();
        this.setLocationRelativeTo(null);
        this.setTitle("CORTE DE CAJA");
        ventasTable.getTableHeader().setReorderingAllowed(false); //evitar que las columnas se editen
        LlenarTable("select (ventas.idVenta,usuarios.nombreUsuario,ventas.numCaja,ventas.fechaVenta,ventas.totalVenta,"
                + "ventas.totalGanancia,ventas.cantidadProductos) from ventas"
                + " inner join usuarios on ventas.idUsuarioFK=usuarios.idUsuario");
        LlenarComboBox();
    }
    
    //llenar los combobox
    private void LlenarComboBox(){
        //removemos los items de los combobox
        CBCajero.removeAllItems();
        
        String [][] respuesta= cliente.consultaSelect("select (nombreUsuario) from usuarios where (idRolFK=2 || idRolFK=3)");
        
        for(int i=1;i<respuesta.length;i++){
            CBCajero.addItem(respuesta[i][0]);
        }
    }
    
    //llenar la tabla segun sus registros
    private void LlenarTable(String query){
        for (int i = (model_corte.getRowCount() - 1); i >= 0; i--) // limpiamos tabla
            model_corte.removeRow(i);
//        28ae5f6449
        TableRowSorter<TableModel> orden = new TableRowSorter<TableModel>((DefaultTableModel)ventasTable.getModel()); // modelo para la tabla
        ventasTable.setRowSorter(orden); // add el ordenamiento
        String [][] res=cliente.consultaSelect(query);
        // recorremos el resultado de la ocnsulta
        for(int j=1;j<res.length;j++){
            model_corte.addRow(res[j]); // add a el modelo de l atabla
        }
    }
    
    //obtener columnas de la cabecera de la tabla
    private String[] getColumnas(){ // columnas para la tabla
        return new String[]{"Num. venta","Usuario","Caja","Fecha","Total venta","Ganancia","Productos"};
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        DateRegistro = new com.toedter.calendar.JDateChooser();
        jScrollPane1 = new javax.swing.JScrollPane();
        ventasTable = new javax.swing.JTable();
        BtnSalirRV = new javax.swing.JButton();
        BtnBuscarRV = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        CBCajero = new javax.swing.JComboBox<>();
        BtnHome = new javax.swing.JButton();
        BtnBack = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setText("Registro de Ventas");

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel3.setText("Fecha:");

        ventasTable.setModel(model_corte);
        jScrollPane1.setViewportView(ventasTable);

        BtnSalirRV.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/error.png"))); // NOI18N
        BtnSalirRV.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnSalirRVActionPerformed(evt);
            }
        });

        BtnBuscarRV.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/research.png"))); // NOI18N
        BtnBuscarRV.setText("Buscar");
        BtnBuscarRV.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnBuscarRVActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel4.setText("Cajero:");

        BtnHome.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/house (3).png"))); // NOI18N
        BtnHome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnHomeActionPerformed(evt);
            }
        });

        BtnBack.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/back (1).png"))); // NOI18N
        BtnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnBackActionPerformed(evt);
            }
        });

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/form (2).png"))); // NOI18N

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(131, 131, 131)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4))
                        .addGap(28, 28, 28)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(CBCajero, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(DateRegistro, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 183, Short.MAX_VALUE)
                        .addComponent(BtnBuscarRV)
                        .addGap(101, 101, 101))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(BtnBack, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(293, 293, 293)
                        .addComponent(BtnHome, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(BtnSalirRV, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel5)
                .addGap(18, 18, 18)
                .addComponent(jLabel1)
                .addGap(227, 227, 227))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(BtnSalirRV)
                    .addComponent(BtnHome)
                    .addComponent(BtnBack))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel5)
                    .addComponent(jLabel1))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(CBCajero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(DateRegistro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addComponent(BtnBuscarRV))
                .addGap(39, 39, 39)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 179, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BtnSalirRVActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnSalirRVActionPerformed
        System.exit(0);       // TODO add your handling code here:
    }//GEN-LAST:event_BtnSalirRVActionPerformed

    private void BtnBuscarRVActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnBuscarRVActionPerformed
        String cajero=CBCajero.getSelectedItem().toString();
        LlenarTable("select (ventas.idVenta,usuarios.nombreUsuario,ventas.numCaja,ventas.fechaVenta,ventas.totalVenta,"
                + "ventas.totalGanancia,ventas.cantidadProductos) from ventas"
                + " inner join usuarios on ventas.idUsuarioFK=usuarios.idUsuario where usuarios.nombreUsuario="
                +cajero+" && ventas.fechaVenta="+new SimpleDateFormat("yyyy-MM-dd").format(DateRegistro.getDate()));
    }//GEN-LAST:event_BtnBuscarRVActionPerformed

    private void BtnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnBackActionPerformed
        MenuPrincipal men = new MenuPrincipal(cliente,empleado);
        men.setVisible(true);
        this.setVisible(false);
        this.dispose();
    }//GEN-LAST:event_BtnBackActionPerformed

    private void BtnHomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnHomeActionPerformed
        MenuPrincipal zz = new MenuPrincipal(cliente,empleado);
         zz.setVisible(true);
         this.setVisible(false);
        this.dispose();
    }//GEN-LAST:event_BtnHomeActionPerformed

   

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnBack;
    private javax.swing.JButton BtnBuscarRV;
    private javax.swing.JButton BtnHome;
    private javax.swing.JButton BtnSalirRV;
    private javax.swing.JComboBox<String> CBCajero;
    private com.toedter.calendar.JDateChooser DateRegistro;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable ventasTable;
    // End of variables declaration//GEN-END:variables
}
